.TH TUXI 1
.SH NAME
TUXI
.SH SYNOPSIS
\fBtuxi\fR [\fB\-h\fR|\fB\-r\fR|\fB\-q\fR] \fIquery
.SH DESCRIPTION
TUXI uses pup to scrape Google search results and SERPs. 
.SH OPTIONS
.PP
\fB\-h\fR
.RS 4
Show help message and exit.
.RE
.PP
\fB\-r\fR
.RS 4
Raw search results.
.P
(no pretty output, no colors)
.RE
.PP
\fB\-q\fR
.RS 4
Only output search results.
.P
(silences "Did you mean?", greeting, usage)

.SH FEATURES
.B Answers questions
.PP
.B Gives corrections (ex. typos in search query)
.PP
.B Shows weather in Celsius and Fahrenheit
.PP
.B Does math
.PP
.B Shows lyrics
.PP
.B Does unit conversions
.PP
.B Does currency conversions
.PP
.B Translates

.SH BUGS
Report bugs at https://github.com/Bugswriter/tuxi/issues
