#!/usr/bin/env sh

# Colour codes
N="\033[0m"    # Reset
R="\033[1;31m" # Red
G="\033[1;32m" # Green
M="\033[1;35m" # Magenta
C="\033[1;36m" # Cyan

help_text() {
    printf "%bUsage:%b tuxi %b<your question>%b\n\ttuxi %b<OPTIONS>%b %b<your question>%b\n\n" "$G" "$N" "$M" "$N" "$C" "$N" "$M" "$N"
    printf "%bOPTIONS:%b\n-r, --raw\tSimplify Tuxi output. Useful for e.g notify-send.\n-h, --help\tDisplays this help message.\n" "$G" "$N"
    printf "\n%bReport bugs to%b https://github.com/Bugswriter/tuxi\n" "$G" "$N"
}

# Argument parsing
case $1 in
    -r|--raw)
        [ -z "$2" ] && echo "Please add query!" && exit 1
        query="$(printf "%s" "$*" | cut -f 2- -d ' ')"
	# Raw formatting functions
        msg() { echo "> $*"; }
        err() { echo "$*"; }
        strip() { echo "$*"; }
    ;;
    -h|--help)
        help_text
        exit 0
    ;;
    -*)
        printf "%bUnknown option%b \"$1\"\n" "$R" "$N"
        exit 1
    ;;
    *)
        query="$*"
	# Normal formatting functions
        msg() { printf "%b>%b %s\n" "$G" "$N" "$*"; } 
        err() { printf "%b%s%b\n" "$R" "$*" "$N"; }
        strip() { printf "%b---%b\n%s\n%b---%b\n" "$G" "$N" "$*" "$G" "$N"; }
    ;;
esac

# Check if dependencies (pup, recode, jq) are installed.
checkdep() {
    while [ -n "$1" ]; do
        if [ ! "$(command -v $1)" ]; then
            err "\"$1\" not found!"
            exit 1
        fi
        shift
    done
}
checkdep pup recode jq

[ $# -le 0 ] && echo "Hi, I am Tuxi.. Ask me something" && help_text | head -n1 && exit $?

user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0"

webpage=$(curl -s -G --compressed "https://www.google.com/search?hl=en_US" --user-agent "$user_agent" --data-urlencode "q=$query")

res0="$(echo "$webpage" | pup 'a.gL9Hy > b text{}' | sed ':a;N;$!ba;s/\n/ /g'| recode html..ISO-8859-1)"
[ -n "$res0" ] && msg "u mean $res0?"

list=$(echo "$webpage" | pup 'div.dAassd json{}'  | jq -r '.[] | .children | .[] | .text' | sed ':a;N;$!ba;s/\n/ /g' | sed 's/null/\n/g' | awk '{$1=$1;print "* " $0}' | sed '/^* $/d'| recode html..ISO-8859-1)
[ -n "$list" ] && strip "$list" && exit

res1="$(echo "$webpage" | pup 'div.zCubwf text{}' | tr -d '\n' | recode html..ISO-8859-1)"
[ -n "$res1" ] && strip "$res1" && exit

res2="$(echo "$webpage" | pup 'div.XcVN5d text{}' | recode html..ISO-8859-1)"
[ -n "$res2" ] && strip "$res2" && exit

res3="$(echo "$webpage" | pup 'span.hgKElc text{}' | tr -d '\n' | recode html..ISO-8859-1 | tr ' ' '\0' | xargs -0 -n10)"
[ -n "$res3" ] && strip "$res3" && exit

res4="$(echo "$webpage" | pup 'span.qv3Wpe text{}' | tr -d '\n ' | recode html..ISO-8859-1)"
[ -n "$res4" ] && strip "$res4" && exit

res5="$(echo "$webpage" | pup 'div.bbVIQb text{}' | recode html..ISO-8859-1)"
[ -n "$res5" ] && strip "$res5" && exit

res6="$(echo "$webpage" | pup 'pre.XcVN5d json{}' | jq -r '[.[] | .children | .[] | select(.class!="BCGytf")][1] | .text' | recode html..ISO-8859-1)"
[ -n "$res6" ] && strip "$res6" && exit

tmp="$(echo "$webpage" | pup 'div.kno-rdesc')"

if [ -n "$tmp" ]; then
    strip "$(echo "$tmp" | pup 'span' | sed -n '2p' | awk '{$1=$1;print}' | recode html..ISO-8859-1 | tr ' ' '\0' | xargs -0 -n10)"
else
    err "No Result!" && exit 1
fi

